name: "Deploy DEV workflow"

permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches-ignore:
      - main
    # paths-ignore:
    #   - ".github/**"

env:
  IMAGE_REPO: "devgcshared671"

jobs:
  build_publish:
    name: "Build Docker Image with new Tag"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      # - name: "Login to Azure CLI"
      #   uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
      #   with:
      #     client-id: ${{ vars.SHARED_OWNER_APP_ID }}
      #     tenant-id: ${{ vars.AZ_TENANT_ID }}
      #     subscription-id: ${{ vars.AZ_SHARED_SUBSCRIPTION_ID }}

      # - name: "Login to dev shared ACR"
      #   run: |
      #     echo -e "📡 \033[1mLogging in to dev shared ACR ... \e[0m"
      #     az acr login --name ${IMAGE_REPO}

      - name: "Build Docker image"
        id: image_version
        run: |
          docker build --tag ${IMAGE_REPO}.azurecr.io/pimenricher:${{ github.run_number }}} --file Dockerfile . || exit 1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ env.IMAGE_REPO }}.azurecr.io/pimenricher:${{ github.run_number }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: "Push Docker image"
        run: |
          echo run
          # docker push ${IMAGE_REPO}.azurecr.io/pimenricher:${{ github.run_number }}
